algoritmo "11"
var
   A, B, C, Delta: Real
inicio
      Escreva ("Digite o valor A: ")
      Leia (A)
      Escreva ("Digite o valor B: ")
      Leia (B)
      Escreva ("Digite o valor C: ")
      Leia (C)
      Delta <- B*B - 4 *A*C
      Escreva ("O valor de Delta é ", Delta)

fimalgoritmo

//11) Desenvolva uma lógica que leia os valores de A, B e C de uma equação do
//segundo grau e mostre o valor de Delta.