algoritmo "15"
var
   dias: inteiro
   sala, VD:Real
inicio
      Escreva ("Quantos dias trabalhados: ")
      Leia (dias)
      VD <- 8*25
      sala <- dias*VD
      Escreva ("O salário será de R$", sala:5:2)
fimalgoritmo

//15) Crie um programa que leia o número de dias trabalhados em um mês e mostre o
//salário de um funcionário, sabendo que ele trabalha 8 horas por dia e ganha R$25
//por hora trabalhada.