algoritmo "18"
var
   N, Idade: Inteiro

inicio
      Escreva ("Em qual ano nasceu(yy/yy/yyyy)? ")
      Leia (N)
      Idade <- 2024 - N
      Se (idade >= 16) entao
      Escreva ("Você tem ", idade, " anos e pode votar!")
      Senao
      Escreva ("Você ainda tem", idade, " anos e não pode votar!")
      Fimse
      
fimalgoritmo

//18)Faça um programa que leia o ano de nascimento de uma pessoa, calcule a idade
//dela e depois mostre se ela pode ou não votar.