algoritmo "20"
var
   N: Inteiro
inicio
      Escreva ("Digite um numero inteiro: ")
      Leia (N)
        Se (N % 2 = 0) entao //O módulo % ajuda a saber que se sobrar é IMPAR, mas se o modulo for = 0 é PAR
        Escreva(N, " é PAR")
        senao
        Escreva (N, " é IMPAR")
        Fimse
fimalgoritmo

//20) Desenvolva um programa que leia um número inteiro e mostre se ele é PAR ou ÍMPAR.