Algoritmo "42"
Var
   C, N: inteiro
Inicio
      Escreva ("Digite um valor: ")
      Leia (N)
      C <- 1
      Enquanto (C<=N) faca
         Escreva (C, " ")
         C <- C + 1
      Fimenquanto
      Escreva ("Acabou!")
Fimalgoritmo

//42) Faça um algoritmo que pergunte ao usuário um número inteiro e positivo
//qualquer e mostre uma contagem até esse valor:
//Ex: Digite um valor: 35
//Contagem: 1 2 3 4 5 6 7 ... 33 34 35 Acabou!

//Ajuda em:
// -