algoritmo "6"
var
   Numero, ante, suce: Inteiro
inicio
      Escreva ("Digite um número: ")
      Leia (Numero)
      Ante <- numero -1
      Suce <- numero +1
      Escreval ("O antecessor de ", numero, " é ", ante)
      Escreval ("O Sucessor de ", numero, " é ", suce)
fimalgoritmo

//6) Faça um programa que leia um número inteiro e mostre o seu antecessor e seu
//sucessor.
//Ex:
//Digite um número: 9
//O antecessor de 9 é 8
//O sucessor de 9 é 10