algoritmo "7"
var
   Numero, D, TP: Real
inicio
      Escreva ("Digite um número: ")
      Leia (Numero)
      D <- numero *2
      TP <- numero /3
      Escreval ("O antecessor de ", numero, " é ", D:9:5)
      Escreval ("O Sucessor de ", numero, " é ", TP:9:5)
fimalgoritmo

//7) Crie um algoritmo que leia um número real e mostre na tela o seu dobro e a
//sua terça parte.
//Ex:
//Digite um número: 3.5
//O dobro de 3.5 é 7.0
//A terça parte de 3.5 é 1.16666